In [ ]:
import pandas as pd

In [ ]:
f_name = 'f9'

In [ ]:
cma_es = pd.read_csv(f'{f_name}_cma_es_doe.csv')[['precision', 'f_s']].rename(columns={'precision': 'cma_es_precision'})
cma_es_init = pd.read_csv(f'{f_name}_lhs_initial_doe.csv')[['precision', 'f_s']].rename(columns={'precision': 'lhs_init_precision'})
uniform = pd.read_csv(f'uniform_doe_{f_name}.csv')[['precision', 'f_s']].rename(columns={'precision': 'uniform_precision'})
lhs = pd.read_csv(f'lhs_doe_{f_name}.csv')[['precision', 'f_s']].rename(columns={'precision': 'lhs_precision'})
halton = pd.read_csv(f'halton_doe_{f_name}.csv')[['precision', 'f_s']].rename(columns={'precision': 'halton_precision'})
sobol = pd.read_csv(f'sobol_doe_{f_name}.csv')[['precision', 'f_s']].rename(columns={'precision': 'sobol_precision'})
stats = cma_es.merge(uniform.merge(lhs.merge(sobol.merge(halton.merge(cma_es_init)))))
stats.head()

,cma_es_precision,f_s,uniform_precision,lhs_precision,sobol_precision,halton_precision,lhs_init_precision
0,9.638265e+08,0,1.038478e+09,1.011123e+09,1.059629e+09,9.829581e+08,1.007285e+09
1,1.470738e+09,1,1.692732e+09,1.514662e+09,1.700818e+09,1.448740e+09,1.670876e+09
2,1.802055e+09,2,1.932473e+09,1.911881e+09,1.682018e+09,1.674731e+09,1.569782e+09
3,1.099380e+09,3,1.278125e+09,1.399816e+09,1.270925e+09,1.366131e+09,1.210519e+09
4,7.787730e+08,4,7.287340e+08,7.272189e+08,7.135508e+08,7.216033e+08,6.830691e+08

# CMA-ES vs first individual (generated by LHS)

In [ ]:
cma_init = stats.loc[stats['cma_es_precision'] < stats['lhs_init_precision']]
print(f'CMA-ES improved lhs DoE on {cma_init.shape[0]}, ({100 * cma_init.shape[0] / stats.shape[0]}%) function instances')
cma_init[['f_s', 'cma_es_precision', 'lhs_init_precision']]

CMA-ES improved lhs DoE on 26, (52.0%) function instances

    f_s  cma_es_precision  lhs_init_precision
0     0      9.638265e+08        1.007285e+09
1     1      1.470738e+09        1.670876e+09
3     3      1.099380e+09        1.210519e+09
6     6      7.618765e+08        8.577742e+08
11   11      1.729676e+09        1.818730e+09
12   12      7.251843e+08        7.666850e+08
13   13      6.488300e+08        6.789253e+08
14   14      1.374636e+09        1.418606e+09
17   17      6.737780e+08        6.738731e+08
18   18      1.574886e+09        1.775116e+09
19   19      1.555498e+09        1.743688e+09
21   21      8.670190e+08        8.988464e+08
23   23      1.326588e+09        1.741405e+09
24   24      1.713436e+09        1.714692e+09
28   28      6.046399e+08        6.306042e+08
29   29      6.212835e+08        6.386671e+08
30   30      5.830863e+08        6.019601e+08
31   31      9.316496e+08        9.558278e+08
33   33      1.252576e+09        1.573643e+09
35   35      6.192952e+08        6.232982e+08
38   38      1.675273e+09        1.865487e+09
40   40      1.606151e+09        1.682293e+09
41   41      5.962839e+08        6.021017e+08
42   42      1.152644e+09        1.407083e+09
44   44      1.362602e+09        1.389839e+09
48   48      1.346937e+09        1.464958e+09

# CMA-ES generated vs Uniform

In [ ]:
cma_uniform = stats.loc[stats['cma_es_precision'] < stats['uniform_precision']]
print(f'DoE generated by CMA-ES is better than uniformly sampled DoE on {cma_uniform.shape[0]}, ({100 * cma_uniform.shape[0] / stats.shape[0]}%) function instances')
cma_uniform[['f_s', 'cma_es_precision', 'uniform_precision']]

DoE generated by CMA-ES is better than uniformly sampled DoE on 28, (56.0%) function instances

    f_s  cma_es_precision  uniform_precision
0     0      9.638265e+08       1.038478e+09
1     1      1.470738e+09       1.692732e+09
2     2      1.802055e+09       1.932473e+09
3     3      1.099380e+09       1.278125e+09
5     5      6.728733e+08       6.870679e+08
6     6      7.618765e+08       8.291382e+08
8     8      1.435123e+09       1.672650e+09
9     9      9.576382e+08       1.019179e+09
10   10      1.059555e+09       1.196591e+09
12   12      7.251843e+08       7.394661e+08
13   13      6.488300e+08       6.570606e+08
17   17      6.737780e+08       7.062070e+08
19   19      1.555498e+09       1.560361e+09
21   21      8.670190e+08       8.797840e+08
23   23      1.326588e+09       1.526247e+09
24   24      1.713436e+09       1.813190e+09
28   28      6.046399e+08       6.372115e+08
30   30      5.830863e+08       6.004348e+08
31   31      9.316496e+08       9.852395e+08
33   33      1.252576e+09       1.409465e+09
36   36      1.370077e+09       1.413503e+09
38   38      1.675273e+09       1.708309e+09
42   42      1.152644e+09       1.586023e+09
43   43      1.419765e+09       1.585629e+09
44   44      1.362602e+09       1.556143e+09
45   45      6.368250e+08       6.558599e+08
46   46      1.549022e+09       1.750713e+09
48   48      1.346937e+09       1.659174e+09

# CMA-ES vs LHS

In [ ]:
cma_lhs = stats.loc[stats['cma_es_precision'] < stats['lhs_precision']]
print(f'DoE generated by CMA-ES is better than lhs sampled DoE on {cma_lhs.shape[0]} ({100 * cma_lhs.shape[0] / stats.shape[0]}%) function instances')
cma_lhs[['f_s', 'cma_es_precision', 'lhs_precision']]

DoE generated by CMA-ES is better than lhs sampled DoE on 26 (52.0%) function instances

    f_s  cma_es_precision  lhs_precision
0     0      9.638265e+08   1.011123e+09
1     1      1.470738e+09   1.514662e+09
2     2      1.802055e+09   1.911881e+09
3     3      1.099380e+09   1.399816e+09
5     5      6.728733e+08   6.890538e+08
7     7      1.315950e+09   1.471629e+09
8     8      1.435123e+09   1.449280e+09
9     9      9.576382e+08   9.593512e+08
13   13      6.488300e+08   6.694279e+08
14   14      1.374636e+09   1.387743e+09
18   18      1.574886e+09   1.771458e+09
19   19      1.555498e+09   1.716153e+09
21   21      8.670190e+08   9.140880e+08
23   23      1.326588e+09   1.459571e+09
25   25      1.132170e+09   1.257888e+09
28   28      6.046399e+08   6.297057e+08
30   30      5.830863e+08   5.939613e+08
31   31      9.316496e+08   9.604731e+08
33   33      1.252576e+09   1.378540e+09
34   34      1.403294e+09   1.458971e+09
38   38      1.675273e+09   1.851150e+09
39   39      1.040295e+09   1.044063e+09
41   41      5.962839e+08   6.015166e+08
43   43      1.419765e+09   1.655404e+09
44   44      1.362602e+09   1.809163e+09
48   48      1.346937e+09   1.491924e+09

# CMA-ES vs Sobol

In [ ]:
cma_sobol = stats.loc[stats['cma_es_precision'] < stats['sobol_precision']]
print(f'DoE generated by CMA-ES is better than sobol generated DoE on {cma_sobol.shape[0]} ({100 * cma_sobol.shape[0] / stats.shape[0]}%) function instances')
cma_sobol[['f_s', 'cma_es_precision', 'sobol_precision']]

DoE generated by CMA-ES is better than sobol generated DoE on 29 (58.0%) function instances

    f_s  cma_es_precision  sobol_precision
0     0      9.638265e+08     1.059629e+09
1     1      1.470738e+09     1.700818e+09
3     3      1.099380e+09     1.270925e+09
7     7      1.315950e+09     1.457359e+09
8     8      1.435123e+09     1.808413e+09
10   10      1.059555e+09     1.123682e+09
11   11      1.729676e+09     1.817927e+09
12   12      7.251843e+08     7.670616e+08
13   13      6.488300e+08     6.733610e+08
15   15      9.116001e+08     9.591974e+08
18   18      1.574886e+09     1.783481e+09
19   19      1.555498e+09     1.670950e+09
21   21      8.670190e+08     9.180256e+08
23   23      1.326588e+09     1.848944e+09
26   26      8.381855e+08     8.640043e+08
28   28      6.046399e+08     6.115645e+08
29   29      6.212835e+08     6.371660e+08
30   30      5.830863e+08     6.068357e+08
31   31      9.316496e+08     1.038198e+09
33   33      1.252576e+09     1.398580e+09
34   34      1.403294e+09     1.574772e+09
39   39      1.040295e+09     1.100244e+09
41   41      5.962839e+08     6.098570e+08
42   42      1.152644e+09     1.325107e+09
43   43      1.419765e+09     1.523670e+09
44   44      1.362602e+09     1.872222e+09
45   45      6.368250e+08     6.793889e+08
46   46      1.549022e+09     1.572530e+09
48   48      1.346937e+09     1.459127e+09

# CMA-ES vs Halton

In [ ]:
cma_halton = stats.loc[stats['cma_es_precision'] < stats['halton_precision']]
print(f'DoE generated by CMA-ES is better than halton generated DoE on {cma_halton.shape[0]} ({100 * cma_halton.shape[0] / stats.shape[0]}%) function instances')
cma_halton[['f_s', 'cma_es_precision', 'halton_precision']]

DoE generated by CMA-ES is better than halton generated DoE on 22 (44.0%) function instances

    f_s  cma_es_precision  halton_precision
0     0      9.638265e+08      9.829581e+08
3     3      1.099380e+09      1.366131e+09
5     5      6.728733e+08      7.132691e+08
7     7      1.315950e+09      1.325751e+09
8     8      1.435123e+09      1.745536e+09
9     9      9.576382e+08      9.975269e+08
10   10      1.059555e+09      1.103549e+09
14   14      1.374636e+09      1.687751e+09
20   20      1.577699e+09      1.752553e+09
22   22      5.949536e+08      5.988887e+08
23   23      1.326588e+09      1.643414e+09
27   27      1.728317e+09      1.797983e+09
28   28      6.046399e+08      6.130427e+08
30   30      5.830863e+08      5.932942e+08
33   33      1.252576e+09      1.531084e+09
37   37      1.213308e+09      1.296996e+09
39   39      1.040295e+09      1.083963e+09
41   41      5.962839e+08      6.009435e+08
42   42      1.152644e+09      1.223346e+09
43   43      1.419765e+09      1.420911e+09
44   44      1.362602e+09      1.542148e+09
48   48      1.346937e+09      1.448538e+09

In [ ]:
cma_is_best = stats.loc[(stats['cma_es_precision'] < stats['halton_precision']) & (stats['cma_es_precision'] < stats['uniform_precision']) & (stats['cma_es_precision'] < stats['lhs_precision']) & (stats['cma_es_precision'] < stats['sobol_precision'])]
print(f'DoE generated by CMA-ES is better than an baseline generated DoE on {cma_is_best.shape[0]} ({100 * cma_is_best.shape[0] / stats.shape[0]}%) function instances')
cma_is_best

DoE generated by CMA-ES is better than an baseline generated DoE on 10 (20.0%) function instances

,cma_es_precision,f_s,uniform_precision,lhs_precision,sobol_precision,halton_precision,lhs_init_precision
0,9.638265e+08,0,1.038478e+09,1.011123e+09,1.059629e+09,9.829581e+08,1.007285e+09
3,1.099380e+09,3,1.278125e+09,1.399816e+09,1.270925e+09,1.366131e+09,1.210519e+09
8,1.435123e+09,8,1.672650e+09,1.449280e+09,1.808413e+09,1.745536e+09,1.377197e+09
23,1.326588e+09,23,1.526247e+09,1.459571e+09,1.848944e+09,1.643414e+09,1.741405e+09
28,6.046399e+08,28,6.372115e+08,6.297057e+08,6.115645e+08,6.130427e+08,6.306042e+08
30,5.830863e+08,30,6.004348e+08,5.939613e+08,6.068357e+08,5.932942e+08,6.019601e+08
33,1.252576e+09,33,1.409465e+09,1.378540e+09,1.398580e+09,1.531084e+09,1.573643e+09
43,1.419765e+09,43,1.585629e+09,1.655404e+09,1.523670e+09,1.420911e+09,1.314576e+09
44,1.362602e+09,44,1.556143e+09,1.809163e+09,1.872222e+09,1.542148e+09,1.389839e+09
48,1.346937e+09,48,1.659174e+09,1.491924e+09,1.459127e+09,1.448538e+09,1.464958e+09