In [ ]:
import pandas as pd

In [ ]:
f_name = 'f12'

In [ ]:
cma_es = pd.read_csv(f'{f_name}_cma_es_doe.csv')[['precision', 'f_s']].rename(columns={'precision': 'cma_es_precision'})
cma_es_init = pd.read_csv(f'{f_name}_lhs_initial_doe.csv')[['precision', 'f_s']].rename(columns={'precision': 'lhs_init_precision'})
uniform = pd.read_csv(f'uniform_doe_{f_name}.csv')[['precision', 'f_s']].rename(columns={'precision': 'uniform_precision'})
lhs = pd.read_csv(f'lhs_doe_{f_name}.csv')[['precision', 'f_s']].rename(columns={'precision': 'lhs_precision'})
halton = pd.read_csv(f'halton_doe_{f_name}.csv')[['precision', 'f_s']].rename(columns={'precision': 'halton_precision'})
sobol = pd.read_csv(f'sobol_doe_{f_name}.csv')[['precision', 'f_s']].rename(columns={'precision': 'sobol_precision'})
stats = cma_es.merge(uniform.merge(lhs.merge(sobol.merge(halton.merge(cma_es_init)))))
stats.head()

,cma_es_precision,f_s,uniform_precision,lhs_precision,sobol_precision,halton_precision,lhs_init_precision
0,5.847600e+16,0,7.325318e+16,5.869153e+16,7.055455e+16,5.336431e+16,5.963088e+16
1,1.817846e+20,1,1.816200e+20,1.814926e+20,1.814453e+20,1.816331e+20,1.822327e+20
2,2.342952e+20,2,2.694554e+20,3.057839e+20,2.788650e+20,3.082707e+20,2.608505e+20
3,8.718021e+19,3,9.466968e+19,1.116840e+20,9.668482e+19,1.031606e+20,1.062056e+20
4,1.788637e+14,4,1.699955e+14,1.743605e+14,1.577887e+14,1.716816e+14,1.602054e+14

# CMA-ES vs first individual (generated by LHS)

In [ ]:
cma_init = stats.loc[stats['cma_es_precision'] < stats['lhs_init_precision']]
print(f'CMA-ES improved lhs-generated DoE on {cma_init.shape[0]}, ({100 * cma_init.shape[0] / stats.shape[0]}%) function instances')
cma_init[['f_s', 'cma_es_precision', 'lhs_init_precision']]

CMA-ES improved lhs-generated DoE on 28, (56.0%) function instances

    f_s  cma_es_precision  lhs_init_precision
0     0      5.847600e+16        5.963088e+16
1     1      1.817846e+20        1.822327e+20
2     2      2.342952e+20        2.608505e+20
3     3      8.718021e+19        1.062056e+20
5     5      1.081428e+16        1.667918e+16
6     6      4.946317e+17        5.716745e+17
8     8      3.930018e+15        3.956339e+15
10   10      1.537469e+15        1.880323e+15
16   16      4.633932e+14        4.676507e+14
17   17      5.766454e+14        5.779205e+14
19   19      1.405140e+16        1.745150e+16
21   21      8.390475e+14        8.402536e+14
22   22      9.605423e+14        9.614989e+14
24   24      3.746988e+18        5.801162e+18
27   27      1.047635e+16        1.050532e+16
28   28      1.101526e+20        1.131080e+20
31   31      5.657838e+18        6.516975e+18
33   33      7.636087e+14        7.668562e+14
35   35      1.502900e+16        1.770635e+16
36   36      4.082895e+14        4.155834e+14
38   38      1.875754e+18        2.592072e+18
39   39      3.897176e+19        4.619225e+19
40   40      5.126765e+15        5.478420e+15
41   41      8.691987e+14        8.960680e+14
43   43      1.182209e+15        1.182508e+15
44   44      6.946425e+17        7.201225e+17
48   48      1.535408e+15        1.681716e+15
49   49      7.571338e+14        7.572850e+14

# CMA-ES generated vs Uniform

In [ ]:
cma_uniform = stats.loc[stats['cma_es_precision'] < stats['uniform_precision']]
print(f'DoE generated by CMA-ES is better than uniformly sampled DoE on {cma_uniform.shape[0]}, ({100 * cma_uniform.shape[0] / stats.shape[0]}%) function instances')
cma_uniform[['f_s', 'cma_es_precision', 'uniform_precision']]

DoE generated by CMA-ES is better than uniformly sampled DoE on 26, (52.0%) function instances

    f_s  cma_es_precision  uniform_precision
0     0      5.847600e+16       7.325318e+16
2     2      2.342952e+20       2.694554e+20
3     3      8.718021e+19       9.466968e+19
5     5      1.081428e+16       1.479687e+16
6     6      4.946317e+17       5.381052e+17
8     8      3.930018e+15       4.620375e+15
10   10      1.537469e+15       1.915057e+15
15   15      9.199248e+14       9.200004e+14
17   17      5.766454e+14       5.790269e+14
20   20      4.738751e+15       5.779981e+15
24   24      3.746988e+18       4.552471e+18
27   27      1.047635e+16       1.066863e+16
28   28      1.101526e+20       1.198150e+20
33   33      7.636087e+14       7.659574e+14
35   35      1.502900e+16       1.791870e+16
36   36      4.082895e+14       4.146538e+14
37   37      1.812279e+17       1.844197e+17
38   38      1.875754e+18       2.643602e+18
40   40      5.126765e+15       5.867026e+15
41   41      8.691987e+14       9.169066e+14
44   44      6.946425e+17       7.115191e+17
45   45      2.496853e+17       2.560344e+17
46   46      3.528336e+15       3.822449e+15
47   47      1.703039e+19       1.703629e+19
48   48      1.535408e+15       1.616550e+15
49   49      7.571338e+14       7.573061e+14

# CMA-ES vs LHS

In [ ]:
cma_lhs = stats.loc[stats['cma_es_precision'] < stats['lhs_precision']]
print(f'DoE generated by CMA-ES is better than lhs sampled DoE on {cma_lhs.shape[0]} ({100 * cma_lhs.shape[0] / stats.shape[0]}%) function instances')
cma_lhs[['f_s', 'cma_es_precision', 'lhs_precision']]

DoE generated by CMA-ES is better than lhs sampled DoE on 26 (52.0%) function instances

    f_s  cma_es_precision  lhs_precision
0     0      5.847600e+16   5.869153e+16
2     2      2.342952e+20   3.057839e+20
3     3      8.718021e+19   1.116840e+20
7     7      1.633639e+15   1.658670e+15
8     8      3.930018e+15   5.230652e+15
15   15      9.199248e+14   9.200336e+14
16   16      4.633932e+14   4.670977e+14
17   17      5.766454e+14   5.800760e+14
20   20      4.738751e+15   5.358116e+15
21   21      8.390475e+14   8.396841e+14
22   22      9.605423e+14   9.610283e+14
28   28      1.101526e+20   1.608057e+20
31   31      5.657838e+18   6.814637e+18
32   32      3.627794e+16   3.691337e+16
35   35      1.502900e+16   1.646058e+16
36   36      4.082895e+14   4.478122e+14
37   37      1.812279e+17   1.818814e+17
38   38      1.875754e+18   2.253431e+18
39   39      3.897176e+19   4.228664e+19
40   40      5.126765e+15   5.392491e+15
41   41      8.691987e+14   8.996676e+14
43   43      1.182209e+15   1.185685e+15
44   44      6.946425e+17   7.204141e+17
46   46      3.528336e+15   4.536054e+15
48   48      1.535408e+15   1.812480e+15
49   49      7.571338e+14   7.571964e+14

# CMA-ES vs Sobol

In [ ]:
cma_sobol = stats.loc[stats['cma_es_precision'] < stats['sobol_precision']]
print(f'DoE generated by CMA-ES is better than sobol generated DoE on {cma_sobol.shape[0]} ({100 * cma_sobol.shape[0] / stats.shape[0]}%) function instances')
cma_sobol[['f_s', 'cma_es_precision', 'sobol_precision']]

DoE generated by CMA-ES is better than sobol generated DoE on 23 (46.0%) function instances

    f_s  cma_es_precision  sobol_precision
0     0      5.847600e+16     7.055455e+16
2     2      2.342952e+20     2.788650e+20
3     3      8.718021e+19     9.668482e+19
5     5      1.081428e+16     1.391325e+16
6     6      4.946317e+17     4.954233e+17
7     7      1.633639e+15     1.654643e+15
10   10      1.537469e+15     1.604479e+15
12   12      5.387572e+14     5.467929e+14
17   17      5.766454e+14     5.804475e+14
19   19      1.405140e+16     1.542929e+16
20   20      4.738751e+15     5.074296e+15
21   21      8.390475e+14     8.413338e+14
24   24      3.746988e+18     3.887523e+18
25   25      1.622146e+14     1.702026e+14
30   30      4.531927e+15     4.588936e+15
33   33      7.636087e+14     7.643801e+14
34   34      1.265133e+15     1.322575e+15
36   36      4.082895e+14     4.518349e+14
38   38      1.875754e+18     2.091253e+18
40   40      5.126765e+15     5.301905e+15
44   44      6.946425e+17     7.544607e+17
45   45      2.496853e+17     2.648987e+17
49   49      7.571338e+14     7.573905e+14

# CMA-ES vs Halton

In [ ]:
cma_halton = stats.loc[stats['cma_es_precision'] < stats['halton_precision']]
print(f'DoE generated by CMA-ES is better than halton generated DoE on {cma_halton.shape[0]} ({100 * cma_halton.shape[0] / stats.shape[0]}%) function instances')
cma_halton[['f_s', 'cma_es_precision', 'halton_precision']]

DoE generated by CMA-ES is better than halton generated DoE on 26 (52.0%) function instances

    f_s  cma_es_precision  halton_precision
2     2      2.342952e+20      3.082707e+20
3     3      8.718021e+19      1.031606e+20
5     5      1.081428e+16      1.229994e+16
6     6      4.946317e+17      5.274619e+17
7     7      1.633639e+15      1.640928e+15
9     9      1.177292e+15      1.448072e+15
10   10      1.537469e+15      1.905197e+15
15   15      9.199248e+14      9.200890e+14
16   16      4.633932e+14      4.677877e+14
17   17      5.766454e+14      5.820585e+14
19   19      1.405140e+16      1.472085e+16
21   21      8.390475e+14      8.393077e+14
24   24      3.746988e+18      4.934164e+18
28   28      1.101526e+20      1.328887e+20
29   29      5.291592e+14      5.366717e+14
30   30      4.531927e+15      4.720005e+15
32   32      3.627794e+16      4.044451e+16
33   33      7.636087e+14      7.662684e+14
35   35      1.502900e+16      2.019749e+16
38   38      1.875754e+18      2.009722e+18
39   39      3.897176e+19      4.194729e+19
40   40      5.126765e+15      5.372923e+15
41   41      8.691987e+14      9.206589e+14
43   43      1.182209e+15      1.188427e+15
44   44      6.946425e+17      7.747039e+17
49   49      7.571338e+14      7.572277e+14

In [ ]:
cma_is_best = stats.loc[(stats['cma_es_precision'] < stats['halton_precision']) & (stats['cma_es_precision'] < stats['uniform_precision']) & (stats['cma_es_precision'] < stats['lhs_precision']) & (stats['cma_es_precision'] < stats['sobol_precision'])]
print(f'DoE generated by CMA-ES is better than any baseline generated DoE on {cma_is_best.shape[0]} ({100 * cma_is_best.shape[0] / stats.shape[0]}%) function instances')
cma_is_best

DoE generated by CMA-ES is better than any baseline generated DoE on 7 (14.0%) function instances

,cma_es_precision,f_s,uniform_precision,lhs_precision,sobol_precision,halton_precision,lhs_init_precision
2,2.342952e+20,2,2.694554e+20,3.057839e+20,2.788650e+20,3.082707e+20,2.608505e+20
3,8.718021e+19,3,9.466968e+19,1.116840e+20,9.668482e+19,1.031606e+20,1.062056e+20
17,5.766454e+14,17,5.790269e+14,5.800760e+14,5.804475e+14,5.820585e+14,5.779205e+14
38,1.875754e+18,38,2.643602e+18,2.253431e+18,2.091253e+18,2.009722e+18,2.592072e+18
40,5.126765e+15,40,5.867026e+15,5.392491e+15,5.301905e+15,5.372923e+15,5.478420e+15
44,6.946425e+17,44,7.115191e+17,7.204141e+17,7.544607e+17,7.747039e+17,7.201225e+17
49,7.571338e+14,49,7.573061e+14,7.571964e+14,7.573905e+14,7.572277e+14,7.572850e+14