In [ ]:
import pandas as pd

In [ ]:
f_name = 'f13'

In [ ]:
cma_es = pd.read_csv(f'{f_name}_cma_es_doe.csv')[['precision', 'f_s']].rename(columns={'precision': 'cma_es_precision'})
cma_es_init = pd.read_csv(f'{f_name}_lhs_initial_doe.csv')[['precision', 'f_s']].rename(columns={'precision': 'lhs_init_precision'})
uniform = pd.read_csv(f'uniform_doe_{f_name}.csv')[['precision', 'f_s']].rename(columns={'precision': 'uniform_precision'})
lhs = pd.read_csv(f'lhs_doe_{f_name}.csv')[['precision', 'f_s']].rename(columns={'precision': 'lhs_precision'})
halton = pd.read_csv(f'halton_doe_{f_name}.csv')[['precision', 'f_s']].rename(columns={'precision': 'halton_precision'})
sobol = pd.read_csv(f'sobol_doe_{f_name}.csv')[['precision', 'f_s']].rename(columns={'precision': 'sobol_precision'})
stats = cma_es.merge(uniform.merge(lhs.merge(sobol.merge(halton.merge(cma_es_init)))))
stats.head()

,cma_es_precision,f_s,uniform_precision,lhs_precision,sobol_precision,halton_precision,lhs_init_precision
0,5.843050e+05,0,5.679551e+05,5.974984e+05,5.784878e+05,5.562766e+05,5.900195e+05
1,8.857774e+05,1,8.540513e+05,8.597251e+05,8.819033e+05,8.730056e+05,8.803148e+05
2,3.317913e+05,2,3.359801e+05,3.456366e+05,3.331034e+05,3.231789e+05,3.475389e+05
3,4.210979e+05,3,4.064623e+05,4.193420e+05,4.250172e+05,4.202274e+05,4.197913e+05
4,2.043094e+06,4,2.021601e+06,2.039404e+06,2.042577e+06,2.056891e+06,2.007306e+06

# CMA-ES vs first individual (generated by LHS)

In [ ]:
cma_init = stats.loc[stats['cma_es_precision'] < stats['lhs_init_precision']]
print(f'CMA-ES improved lhs-generated DoE on {cma_init.shape[0]}, ({100 * cma_init.shape[0] / stats.shape[0]}%) function instances')
cma_init[['f_s', 'cma_es_precision', 'lhs_init_precision']]

CMA-ES improved lhs-generated DoE on 24, (48.0%) function instances

    f_s  cma_es_precision  lhs_init_precision
0     0      5.843050e+05        5.900195e+05
2     2      3.317913e+05        3.475389e+05
5     5      1.191424e+06        1.221366e+06
6     6      4.750921e+05        4.818616e+05
7     7      4.508358e+05        4.617834e+05
9     9      1.067635e+06        1.078001e+06
10   10      2.604073e+05        2.638697e+05
14   14      7.065593e+05        7.416532e+05
18   18      6.858154e+05        6.866777e+05
19   19      7.086881e+05        7.111811e+05
20   20      3.254696e+06        3.289256e+06
21   21      5.825239e+05        5.835608e+05
22   22      8.760078e+05        8.809348e+05
23   23      9.362966e+05        9.367315e+05
25   25      1.041993e+06        1.061612e+06
26   26      1.494665e+05        1.537282e+05
30   30      1.685375e+06        1.687348e+06
31   31      2.026388e+05        2.041379e+05
34   34      5.647781e+05        5.663400e+05
36   36      1.949762e+05        1.952161e+05
43   43      1.683994e+06        1.698043e+06
44   44      2.173227e+06        2.191897e+06
46   46      7.997268e+05        8.150647e+05
49   49      7.387940e+05        7.418523e+05

# CMA-ES generated vs Uniform

In [ ]:
cma_uniform = stats.loc[stats['cma_es_precision'] < stats['uniform_precision']]
print(f'DoE generated by CMA-ES is better than uniformly sampled DoE on {cma_uniform.shape[0]}, ({100 * cma_uniform.shape[0] / stats.shape[0]}%) function instances')
cma_uniform[['f_s', 'cma_es_precision', 'uniform_precision']]

DoE generated by CMA-ES is better than uniformly sampled DoE on 22, (44.0%) function instances

    f_s  cma_es_precision  uniform_precision
2     2      3.317913e+05       3.359801e+05
5     5      1.191424e+06       1.237222e+06
7     7      4.508358e+05       4.611287e+05
9     9      1.067635e+06       1.082105e+06
10   10      2.604073e+05       2.619859e+05
13   13      1.258012e+06       1.265589e+06
16   16      8.032741e+05       8.097786e+05
21   21      5.825239e+05       6.127352e+05
25   25      1.041993e+06       1.056514e+06
26   26      1.494665e+05       1.560834e+05
29   29      1.731237e+06       1.751928e+06
30   30      1.685375e+06       1.687479e+06
32   32      7.209381e+05       7.254545e+05
33   33      1.237585e+06       1.239436e+06
34   34      5.647781e+05       5.678790e+05
36   36      1.949762e+05       1.967580e+05
37   37      1.067381e+06       1.073510e+06
41   41      4.696595e+05       4.706646e+05
42   42      8.998434e+05       9.008437e+05
43   43      1.683994e+06       1.710534e+06
47   47      7.042441e+05       7.083995e+05
49   49      7.387940e+05       7.391144e+05

# CMA-ES vs LHS

In [ ]:
cma_lhs = stats.loc[stats['cma_es_precision'] < stats['lhs_precision']]
print(f'DoE generated by CMA-ES is better than lhs sampled DoE on {cma_lhs.shape[0]} ({100 * cma_lhs.shape[0] / stats.shape[0]}%) function instances')
cma_lhs[['f_s', 'cma_es_precision', 'lhs_precision']]

DoE generated by CMA-ES is better than lhs sampled DoE on 26 (52.0%) function instances

    f_s  cma_es_precision  lhs_precision
0     0      5.843050e+05   5.974984e+05
2     2      3.317913e+05   3.456366e+05
5     5      1.191424e+06   1.237450e+06
6     6      4.750921e+05   4.763692e+05
7     7      4.508358e+05   4.594801e+05
9     9      1.067635e+06   1.077152e+06
10   10      2.604073e+05   2.622556e+05
14   14      7.065593e+05   7.194444e+05
15   15      2.868069e+06   3.026070e+06
16   16      8.032741e+05   8.234916e+05
18   18      6.858154e+05   6.872195e+05
19   19      7.086881e+05   7.090470e+05
21   21      5.825239e+05   6.482184e+05
22   22      8.760078e+05   9.128436e+05
24   24      1.304076e+06   1.304416e+06
25   25      1.041993e+06   1.067356e+06
27   27      5.686519e+06   5.686739e+06
29   29      1.731237e+06   1.754870e+06
30   30      1.685375e+06   1.689801e+06
32   32      7.209381e+05   7.464843e+05
35   35      3.622310e+05   3.703201e+05
37   37      1.067381e+06   1.071601e+06
39   39      9.254693e+05   9.344998e+05
44   44      2.173227e+06   2.191032e+06
46   46      7.997268e+05   8.128522e+05
49   49      7.387940e+05   7.391100e+05

# CMA-ES vs Sobol

In [ ]:
cma_sobol = stats.loc[stats['cma_es_precision'] < stats['sobol_precision']]
print(f'DoE generated by CMA-ES is better than sobol generated DoE on {cma_sobol.shape[0]} ({100 * cma_sobol.shape[0] / stats.shape[0]}%) function instances')
cma_sobol[['f_s', 'cma_es_precision', 'sobol_precision']]

DoE generated by CMA-ES is better than sobol generated DoE on 27 (54.0%) function instances

    f_s  cma_es_precision  sobol_precision
2     2      3.317913e+05     3.331034e+05
3     3      4.210979e+05     4.250172e+05
5     5      1.191424e+06     1.210680e+06
6     6      4.750921e+05     4.773031e+05
7     7      4.508358e+05     4.612460e+05
9     9      1.067635e+06     1.072957e+06
12   12      7.684089e+05     7.780347e+05
13   13      1.258012e+06     1.267023e+06
15   15      2.868069e+06     2.945140e+06
16   16      8.032741e+05     8.239289e+05
20   20      3.254696e+06     3.258200e+06
21   21      5.825239e+05     6.022809e+05
22   22      8.760078e+05     8.968360e+05
25   25      1.041993e+06     1.060462e+06
26   26      1.494665e+05     1.511342e+05
29   29      1.731237e+06     1.750317e+06
30   30      1.685375e+06     1.686331e+06
31   31      2.026388e+05     2.035925e+05
33   33      1.237585e+06     1.237651e+06
36   36      1.949762e+05     1.958906e+05
37   37      1.067381e+06     1.082821e+06
39   39      9.254693e+05     9.354645e+05
43   43      1.683994e+06     1.686159e+06
44   44      2.173227e+06     2.188137e+06
45   45      1.159211e+06     1.160009e+06
46   46      7.997268e+05     8.036154e+05
49   49      7.387940e+05     7.417819e+05

# CMA-ES vs Halton

In [ ]:
cma_halton = stats.loc[stats['cma_es_precision'] < stats['halton_precision']]
print(f'DoE generated by CMA-ES is better than halton generated DoE on {cma_halton.shape[0]} ({100 * cma_halton.shape[0] / stats.shape[0]}%) function instances')
cma_halton[['f_s', 'cma_es_precision', 'halton_precision']]

DoE generated by CMA-ES is better than halton generated DoE on 24 (48.0%) function instances

    f_s  cma_es_precision  halton_precision
4     4      2.043094e+06      2.056891e+06
5     5      1.191424e+06      1.241117e+06
6     6      4.750921e+05      4.793303e+05
7     7      4.508358e+05      4.585490e+05
8     8      3.624092e+05      3.718419e+05
9     9      1.067635e+06      1.072207e+06
10   10      2.604073e+05      2.619784e+05
14   14      7.065593e+05      7.214190e+05
15   15      2.868069e+06      2.924358e+06
16   16      8.032741e+05      8.200874e+05
19   19      7.086881e+05      7.095848e+05
21   21      5.825239e+05      5.924215e+05
25   25      1.041993e+06      1.046471e+06
26   26      1.494665e+05      1.512869e+05
29   29      1.731237e+06      1.758554e+06
30   30      1.685375e+06      1.689534e+06
37   37      1.067381e+06      1.078264e+06
38   38      1.191211e+06      1.192001e+06
39   39      9.254693e+05      9.607652e+05
41   41      4.696595e+05      4.720173e+05
43   43      1.683994e+06      1.739424e+06
44   44      2.173227e+06      2.206121e+06
46   46      7.997268e+05      8.095896e+05
47   47      7.042441e+05      7.043775e+05

In [ ]:
cma_is_best = stats.loc[(stats['cma_es_precision'] < stats['halton_precision']) & (stats['cma_es_precision'] < stats['uniform_precision']) & (stats['cma_es_precision'] < stats['lhs_precision']) & (stats['cma_es_precision'] < stats['sobol_precision'])]
print(f'DoE generated by CMA-ES is better than any baseline generated DoE on {cma_is_best.shape[0]} ({100 * cma_is_best.shape[0] / stats.shape[0]}%) function instances')
cma_is_best

DoE generated by CMA-ES is better than any baseline generated DoE on 9 (18.0%) function instances

,cma_es_precision,f_s,uniform_precision,lhs_precision,sobol_precision,halton_precision,lhs_init_precision
5,1.191424e+06,5,1.237222e+06,1.237450e+06,1.210680e+06,1.241117e+06,1.221366e+06
7,4.508358e+05,7,4.611287e+05,4.594801e+05,4.612460e+05,4.585490e+05,4.617834e+05
9,1.067635e+06,9,1.082105e+06,1.077152e+06,1.072957e+06,1.072207e+06,1.078001e+06
16,8.032741e+05,16,8.097786e+05,8.234916e+05,8.239289e+05,8.200874e+05,7.978208e+05
21,5.825239e+05,21,6.127352e+05,6.482184e+05,6.022809e+05,5.924215e+05,5.835608e+05
25,1.041993e+06,25,1.056514e+06,1.067356e+06,1.060462e+06,1.046471e+06,1.061612e+06
29,1.731237e+06,29,1.751928e+06,1.754870e+06,1.750317e+06,1.758554e+06,1.726257e+06
30,1.685375e+06,30,1.687479e+06,1.689801e+06,1.686331e+06,1.689534e+06,1.687348e+06
37,1.067381e+06,37,1.073510e+06,1.071601e+06,1.082821e+06,1.078264e+06,1.065825e+06